version: '3'
services:
  taurus-expose-auth-ms:
    build: .
    #command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0' --log-to-stdout"
    volumes:
      - .:/myapp
    ports:
      - "8081:8081"
    environment:
      TAURUS_SERVER_URL: https://taurusmaze.co
      CONSUME_SERVER_URL: http://54.39.98.125:4009
      
    networks:
      - taurus-network

networks:
  taurus-network:
    external: true